/*
 * Anonymous API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package ru.boomik.vrnbus.dal.dto

import com.google.gson.annotations.SerializedName
import kotlinx.serialization.Serializable
import java.util.*

/**
 * BusStationDto
 */
@Serializable
class BusStationDto {
    /**
     * Get id
     *
     * @return id
     */
    @SerializedName("id")
    var id = 0

    /**
     * Get name
     *
     * @return name
     */
    @SerializedName("name")
    var name = ""

    /**
     * Get latitude
     *
     * @return latitude
     */
    @SerializedName("latitude")
    var latitude = .0

    /**
     * Get longitude
     *
     * @return longitude
     */
    @SerializedName("longitude")
    var longitude = .0

    /**
     * Get azimuth
     *
     * @return azimuth
     */
    @SerializedName("azimuth")
    var azimuth = 0
    fun id(id: Int): BusStationDto {
        this.id = id
        return this
    }

    fun name(name: String): BusStationDto {
        this.name = name
        return this
    }

    fun latitude(latitude: Double): BusStationDto {
        this.latitude = latitude
        return this
    }

    fun longitude(longitude: Double): BusStationDto {
        this.longitude = longitude
        return this
    }

    fun azimuth(azimuth: Int): BusStationDto {
        this.azimuth = azimuth
        return this
    }

    override fun equals(o: Any?): Boolean {
        if (this === o) {
            return true
        }
        if (o == null || javaClass != o.javaClass) {
            return false
        }
        val busStationDto = o as BusStationDto
        return id == busStationDto.id &&
                name == busStationDto.name &&
                latitude == busStationDto.latitude &&
                longitude == busStationDto.longitude &&
                azimuth == busStationDto.azimuth
    }

    override fun hashCode(): Int {
        return Objects.hash(id, name, latitude, longitude, azimuth)
    }

    override fun toString(): String {
        val sb = StringBuilder()
        sb.append("class BusStationDto {\n")
        sb.append("    id: ").append(toIndentedString(id)).append("\n")
        sb.append("    name: ").append(toIndentedString(name)).append("\n")
        sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n")
        sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n")
        sb.append("    azimuth: ").append(toIndentedString(azimuth)).append("\n")
        sb.append("}")
        return sb.toString()
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private fun toIndentedString(o: Any?): String {
        return o?.toString()?.replace("\n", "\n    ") ?: "null"
    }
}