/*
 * Anonymous API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package ru.boomik.vrnbus.dal.dto

import com.google.gson.annotations.SerializedName
import kotlinx.serialization.Serializable
import java.util.*

/**
 * CarBrandDto
 */
@Serializable
class CarBrandDto {
    /**
     * Get id
     *
     * @return id
     */
    @SerializedName("id")
    var id: Int? = null

    /**
     * Get name
     *
     * @return name
     */
    @SerializedName("name")
    var name: String? = null

    /**
     * Get carTypeId
     *
     * @return carTypeId
     */
    @SerializedName("carTypeId")
    var carTypeId: Int? = null

    /**
     * Get l
     *
     * @return l
     */
    @SerializedName("l")
    var l: String? = null

    /**
     * Get w
     *
     * @return w
     */
    @SerializedName("w")
    var w: String? = null

    /**
     * Get h
     *
     * @return h
     */
    @SerializedName("h")
    var h: String? = null

    /**
     * Get carType
     *
     * @return carType
     */
    @SerializedName("carType")
    var carType: CarTypeDto? = null
    fun id(id: Int?): CarBrandDto {
        this.id = id
        return this
    }

    fun name(name: String?): CarBrandDto {
        this.name = name
        return this
    }

    fun carTypeId(carTypeId: Int?): CarBrandDto {
        this.carTypeId = carTypeId
        return this
    }

    fun l(l: String?): CarBrandDto {
        this.l = l
        return this
    }

    fun w(w: String?): CarBrandDto {
        this.w = w
        return this
    }

    fun h(h: String?): CarBrandDto {
        this.h = h
        return this
    }

    fun carType(carType: CarTypeDto?): CarBrandDto {
        this.carType = carType
        return this
    }

    override fun equals(o: Any?): Boolean {
        if (this === o) {
            return true
        }
        if (o == null || javaClass != o.javaClass) {
            return false
        }
        val carBrandDto = o as CarBrandDto
        return id == carBrandDto.id &&
                name == carBrandDto.name &&
                carTypeId == carBrandDto.carTypeId &&
                l == carBrandDto.l &&
                w == carBrandDto.w &&
                h == carBrandDto.h &&
                carType == carBrandDto.carType
    }

    override fun hashCode(): Int {
        return Objects.hash(id, name, carTypeId, l, w, h, carType)
    }

    override fun toString(): String {
        val sb = StringBuilder()
        sb.append("class CarBrandDto {\n")
        sb.append("    id: ").append(toIndentedString(id)).append("\n")
        sb.append("    name: ").append(toIndentedString(name)).append("\n")
        sb.append("    carTypeId: ").append(toIndentedString(carTypeId)).append("\n")
        sb.append("    l: ").append(toIndentedString(l)).append("\n")
        sb.append("    w: ").append(toIndentedString(w)).append("\n")
        sb.append("    h: ").append(toIndentedString(h)).append("\n")
        sb.append("    carType: ").append(toIndentedString(carType)).append("\n")
        sb.append("}")
        return sb.toString()
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private fun toIndentedString(o: Any?): String {
        return o?.toString()?.replace("\n", "\n    ") ?: "null"
    }
}