/*
 * Anonymous API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ru.boomik.vrnbus.dal.dto;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * FindPathRouteDirectionDto
 */

public class FindPathRouteDirectionDto {
  @SerializedName("routes")
  private List<NamedEntityDto> routes = null;

  @SerializedName("busStations")
  private List<BusStationDto> busStations = null;

  public FindPathRouteDirectionDto routes(List<NamedEntityDto> routes) {
    this.routes = routes;
    return this;
  }

  public FindPathRouteDirectionDto addRoutesItem(NamedEntityDto routesItem) {
    if (this.routes == null) {
      this.routes = new ArrayList<NamedEntityDto>();
    }
    this.routes.add(routesItem);
    return this;
  }

   /**
   * Get routes
   * @return routes
  **/

  public List<NamedEntityDto> getRoutes() {
    return routes;
  }

  public void setRoutes(List<NamedEntityDto> routes) {
    this.routes = routes;
  }

  public FindPathRouteDirectionDto busStations(List<BusStationDto> busStations) {
    this.busStations = busStations;
    return this;
  }

  public FindPathRouteDirectionDto addBusStationsItem(BusStationDto busStationsItem) {
    if (this.busStations == null) {
      this.busStations = new ArrayList<BusStationDto>();
    }
    this.busStations.add(busStationsItem);
    return this;
  }

   /**
   * Get busStations
   * @return busStations
  **/

  public List<BusStationDto> getBusStations() {
    return busStations;
  }

  public void setBusStations(List<BusStationDto> busStations) {
    this.busStations = busStations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FindPathRouteDirectionDto findPathRouteDirectionDto = (FindPathRouteDirectionDto) o;
    return Objects.equals(this.routes, findPathRouteDirectionDto.routes) &&
        Objects.equals(this.busStations, findPathRouteDirectionDto.busStations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(routes, busStations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FindPathRouteDirectionDto {\n");
    
    sb.append("    routes: ").append(toIndentedString(routes)).append("\n");
    sb.append("    busStations: ").append(toIndentedString(busStations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

