/*
 * Anonymous API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package ru.boomik.vrnbus.dal.dto

import com.google.gson.annotations.SerializedName
import kotlinx.serialization.Serializable
import java.util.*

/**
 * FindPathRouteDirectionDto
 */
@Serializable
class FindPathRouteDirectionDto {
    @SerializedName("routes")
    private var routes: MutableList<NamedEntityDto>? = null

    @SerializedName("busStations")
    private var busStations: MutableList<BusStationDto>? = null
    fun routes(routes: MutableList<NamedEntityDto>?): FindPathRouteDirectionDto {
        this.routes = routes
        return this
    }

    fun addRoutesItem(routesItem: NamedEntityDto): FindPathRouteDirectionDto {
        if (routes == null) {
            routes = ArrayList()
        }
        routes!!.add(routesItem)
        return this
    }

    /**
     * Get routes
     *
     * @return routes
     */
    fun getRoutes(): List<NamedEntityDto>? {
        return routes
    }

    fun setRoutes(routes: MutableList<NamedEntityDto>?) {
        this.routes = routes
    }

    fun busStations(busStations: MutableList<BusStationDto>?): FindPathRouteDirectionDto {
        this.busStations = busStations
        return this
    }

    fun addBusStationsItem(busStationsItem: BusStationDto): FindPathRouteDirectionDto {
        if (busStations == null) {
            busStations = ArrayList()
        }
        busStations!!.add(busStationsItem)
        return this
    }

    /**
     * Get busStations
     *
     * @return busStations
     */
    fun getBusStations(): List<BusStationDto>? {
        return busStations
    }

    fun setBusStations(busStations: MutableList<BusStationDto>?) {
        this.busStations = busStations
    }

    override fun equals(o: Any?): Boolean {
        if (this === o) {
            return true
        }
        if (o == null || javaClass != o.javaClass) {
            return false
        }
        val findPathRouteDirectionDto = o as FindPathRouteDirectionDto
        return routes == findPathRouteDirectionDto.routes &&
                busStations == findPathRouteDirectionDto.busStations
    }

    override fun hashCode(): Int {
        return Objects.hash(routes, busStations)
    }

    override fun toString(): String {
        val sb = StringBuilder()
        sb.append("class FindPathRouteDirectionDto {\n")
        sb.append("    routes: ").append(toIndentedString(routes)).append("\n")
        sb.append("    busStations: ").append(toIndentedString(busStations)).append("\n")
        sb.append("}")
        return sb.toString()
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private fun toIndentedString(o: Any?): String {
        return o?.toString()?.replace("\n", "\n    ") ?: "null"
    }
}