/*
 * Anonymous API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package ru.boomik.vrnbus.dal.dto

import com.google.gson.annotations.SerializedName
import kotlinx.serialization.Serializable
import java.util.*

/**
 * FindPathDto
 */
@Serializable
class FindPathDto {
    @SerializedName("directDirections")
    private var directDirections: MutableList<FindPathRouteDirectionDto>? = null

    @SerializedName("oneTransferDirections")
    private var oneTransferDirections: MutableList<List<FindPathRouteDirectionDto>>? = null
    fun directDirections(directDirections: MutableList<FindPathRouteDirectionDto>?): FindPathDto {
        this.directDirections = directDirections
        return this
    }

    fun addDirectDirectionsItem(directDirectionsItem: FindPathRouteDirectionDto): FindPathDto {
        if (directDirections == null) {
            directDirections = ArrayList()
        }
        directDirections!!.add(directDirectionsItem)
        return this
    }

    /**
     * Get directDirections
     *
     * @return directDirections
     */
    fun getDirectDirections(): List<FindPathRouteDirectionDto>? {
        return directDirections
    }

    fun setDirectDirections(directDirections: MutableList<FindPathRouteDirectionDto>?) {
        this.directDirections = directDirections
    }

    fun oneTransferDirections(oneTransferDirections: MutableList<List<FindPathRouteDirectionDto>>?): FindPathDto {
        this.oneTransferDirections = oneTransferDirections
        return this
    }

    fun addOneTransferDirectionsItem(oneTransferDirectionsItem: List<FindPathRouteDirectionDto>): FindPathDto {
        if (oneTransferDirections == null) {
            oneTransferDirections = ArrayList()
        }
        oneTransferDirections!!.add(oneTransferDirectionsItem)
        return this
    }

    /**
     * Get oneTransferDirections
     *
     * @return oneTransferDirections
     */
    fun getOneTransferDirections(): List<List<FindPathRouteDirectionDto>>? {
        return oneTransferDirections
    }

    fun setOneTransferDirections(oneTransferDirections: MutableList<List<FindPathRouteDirectionDto>>?) {
        this.oneTransferDirections = oneTransferDirections
    }

    override fun equals(o: Any?): Boolean {
        if (this === o) {
            return true
        }
        if (o == null || javaClass != o.javaClass) {
            return false
        }
        val findPathDto = o as FindPathDto
        return directDirections == findPathDto.directDirections &&
                oneTransferDirections == findPathDto.oneTransferDirections
    }

    override fun hashCode(): Int {
        return Objects.hash(directDirections, oneTransferDirections)
    }

    override fun toString(): String {
        val sb = StringBuilder()
        sb.append("class FindPathDto {\n")
        sb.append("    directDirections: ").append(toIndentedString(directDirections)).append("\n")
        sb.append("    oneTransferDirections: ").append(toIndentedString(oneTransferDirections)).append("\n")
        sb.append("}")
        return sb.toString()
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private fun toIndentedString(o: Any?): String {
        return o?.toString()?.replace("\n", "\n    ") ?: "null"
    }
}