/*
 * Anonymous API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package ru.boomik.vrnbus.dal.dto

import com.google.gson.annotations.SerializedName
import kotlinx.serialization.Serializable
import java.util.*

/**
 * GranitDto
 */
@Serializable
class GranitDto {
    /**
     * Get id
     *
     * @return id
     */
    @SerializedName("id")
    var id: Int? = null

    /**
     * Get blockNumber
     *
     * @return blockNumber
     */
    @SerializedName("blockNumber")
    var blockNumber: Int? = null

    /**
     * Get blockTypeId
     *
     * @return blockTypeId
     */
    @SerializedName("blockTypeId")
    var blockTypeId: Int? = null

    /**
     * Get objectId
     *
     * @return objectId
     */
    @SerializedName("objectId")
    var objectId: Int? = null

    /**
     * Get blockType
     *
     * @return blockType
     */
    @SerializedName("blockType")
    var blockType: BlockTypeDto? = null
    fun id(id: Int?): GranitDto {
        this.id = id
        return this
    }

    fun blockNumber(blockNumber: Int?): GranitDto {
        this.blockNumber = blockNumber
        return this
    }

    fun blockTypeId(blockTypeId: Int?): GranitDto {
        this.blockTypeId = blockTypeId
        return this
    }

    fun objectId(objectId: Int?): GranitDto {
        this.objectId = objectId
        return this
    }

    fun blockType(blockType: BlockTypeDto?): GranitDto {
        this.blockType = blockType
        return this
    }

    override fun equals(o: Any?): Boolean {
        if (this === o) {
            return true
        }
        if (o == null || javaClass != o.javaClass) {
            return false
        }
        val granitDto = o as GranitDto
        return id == granitDto.id &&
                blockNumber == granitDto.blockNumber &&
                blockTypeId == granitDto.blockTypeId &&
                objectId == granitDto.objectId &&
                blockType == granitDto.blockType
    }

    override fun hashCode(): Int {
        return Objects.hash(id, blockNumber, blockTypeId, objectId, blockType)
    }

    override fun toString(): String {
        val sb = StringBuilder()
        sb.append("class GranitDto {\n")
        sb.append("    id: ").append(toIndentedString(id)).append("\n")
        sb.append("    blockNumber: ").append(toIndentedString(blockNumber)).append("\n")
        sb.append("    blockTypeId: ").append(toIndentedString(blockTypeId)).append("\n")
        sb.append("    objectId: ").append(toIndentedString(objectId)).append("\n")
        sb.append("    blockType: ").append(toIndentedString(blockType)).append("\n")
        sb.append("}")
        return sb.toString()
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private fun toIndentedString(o: Any?): String {
        return o?.toString()?.replace("\n", "\n    ") ?: "null"
    }
}