/*
 * Anonymous API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.binwell.dal.dto;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

/**
 * CarBrandDto
 */

public class CarBrandDto {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("carTypeId")
  private Integer carTypeId = null;

  @SerializedName("l")
  private String l = null;

  @SerializedName("w")
  private String w = null;

  @SerializedName("h")
  private String h = null;

  @SerializedName("carType")
  private CarTypeDto carType = null;

  public CarBrandDto id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/

  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public CarBrandDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CarBrandDto carTypeId(Integer carTypeId) {
    this.carTypeId = carTypeId;
    return this;
  }

   /**
   * Get carTypeId
   * @return carTypeId
  **/

  public Integer getCarTypeId() {
    return carTypeId;
  }

  public void setCarTypeId(Integer carTypeId) {
    this.carTypeId = carTypeId;
  }

  public CarBrandDto l(String l) {
    this.l = l;
    return this;
  }

   /**
   * Get l
   * @return l
  **/

  public String getL() {
    return l;
  }

  public void setL(String l) {
    this.l = l;
  }

  public CarBrandDto w(String w) {
    this.w = w;
    return this;
  }

   /**
   * Get w
   * @return w
  **/

  public String getW() {
    return w;
  }

  public void setW(String w) {
    this.w = w;
  }

  public CarBrandDto h(String h) {
    this.h = h;
    return this;
  }

   /**
   * Get h
   * @return h
  **/

  public String getH() {
    return h;
  }

  public void setH(String h) {
    this.h = h;
  }

  public CarBrandDto carType(CarTypeDto carType) {
    this.carType = carType;
    return this;
  }

   /**
   * Get carType
   * @return carType
  **/

  public CarTypeDto getCarType() {
    return carType;
  }

  public void setCarType(CarTypeDto carType) {
    this.carType = carType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CarBrandDto carBrandDto = (CarBrandDto) o;
    return Objects.equals(this.id, carBrandDto.id) &&
        Objects.equals(this.name, carBrandDto.name) &&
        Objects.equals(this.carTypeId, carBrandDto.carTypeId) &&
        Objects.equals(this.l, carBrandDto.l) &&
        Objects.equals(this.w, carBrandDto.w) &&
        Objects.equals(this.h, carBrandDto.h) &&
        Objects.equals(this.carType, carBrandDto.carType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, carTypeId, l, w, h, carType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CarBrandDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    carTypeId: ").append(toIndentedString(carTypeId)).append("\n");
    sb.append("    l: ").append(toIndentedString(l)).append("\n");
    sb.append("    w: ").append(toIndentedString(w)).append("\n");
    sb.append("    h: ").append(toIndentedString(h)).append("\n");
    sb.append("    carType: ").append(toIndentedString(carType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

