/*
 * Anonymous API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.binwell.dal.dto;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * FindPathDto
 */

public class FindPathDto {
  @SerializedName("directDirections")
  private List<FindPathRouteDirectionDto> directDirections = null;

  @SerializedName("oneTransferDirections")
  private List<List<FindPathRouteDirectionDto>> oneTransferDirections = null;

  public FindPathDto directDirections(List<FindPathRouteDirectionDto> directDirections) {
    this.directDirections = directDirections;
    return this;
  }

  public FindPathDto addDirectDirectionsItem(FindPathRouteDirectionDto directDirectionsItem) {
    if (this.directDirections == null) {
      this.directDirections = new ArrayList<FindPathRouteDirectionDto>();
    }
    this.directDirections.add(directDirectionsItem);
    return this;
  }

   /**
   * Get directDirections
   * @return directDirections
  **/

  public List<FindPathRouteDirectionDto> getDirectDirections() {
    return directDirections;
  }

  public void setDirectDirections(List<FindPathRouteDirectionDto> directDirections) {
    this.directDirections = directDirections;
  }

  public FindPathDto oneTransferDirections(List<List<FindPathRouteDirectionDto>> oneTransferDirections) {
    this.oneTransferDirections = oneTransferDirections;
    return this;
  }

  public FindPathDto addOneTransferDirectionsItem(List<FindPathRouteDirectionDto> oneTransferDirectionsItem) {
    if (this.oneTransferDirections == null) {
      this.oneTransferDirections = new ArrayList<List<FindPathRouteDirectionDto>>();
    }
    this.oneTransferDirections.add(oneTransferDirectionsItem);
    return this;
  }

   /**
   * Get oneTransferDirections
   * @return oneTransferDirections
  **/

  public List<List<FindPathRouteDirectionDto>> getOneTransferDirections() {
    return oneTransferDirections;
  }

  public void setOneTransferDirections(List<List<FindPathRouteDirectionDto>> oneTransferDirections) {
    this.oneTransferDirections = oneTransferDirections;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FindPathDto findPathDto = (FindPathDto) o;
    return Objects.equals(this.directDirections, findPathDto.directDirections) &&
        Objects.equals(this.oneTransferDirections, findPathDto.oneTransferDirections);
  }

  @Override
  public int hashCode() {
    return Objects.hash(directDirections, oneTransferDirections);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FindPathDto {\n");
    
    sb.append("    directDirections: ").append(toIndentedString(directDirections)).append("\n");
    sb.append("    oneTransferDirections: ").append(toIndentedString(oneTransferDirections)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

