/*
 * Anonymous API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.binwell.dal.dto;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * NewRouteWithStationsDto
 */

public class NewRouteWithStationsDto {
  @SerializedName("description")
  private String description = null;

  @SerializedName("changeDescription")
  private String changeDescription = null;

  @SerializedName("numberOfBuses")
  private String numberOfBuses = null;

  @SerializedName("intervalOfBuses")
  private String intervalOfBuses = null;

  @SerializedName("newRouteStatus")
  private NamedEntityDto newRouteStatus = null;

  @SerializedName("newRouteBusType")
  private NamedEntityDto newRouteBusType = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    NUMBER_1(1),
    
    NUMBER_2(2);

    private Integer value;

    TypeEnum(Integer value) {
      this.value = value;
    }

    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        Integer value = jsonReader.nextInt();
        return TypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  @SerializedName("forwardDirectionStations")
  private List<Integer> forwardDirectionStations = null;

  @SerializedName("backDirectionStations")
  private List<Integer> backDirectionStations = null;

  public NewRouteWithStationsDto description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public NewRouteWithStationsDto changeDescription(String changeDescription) {
    this.changeDescription = changeDescription;
    return this;
  }

   /**
   * Get changeDescription
   * @return changeDescription
  **/

  public String getChangeDescription() {
    return changeDescription;
  }

  public void setChangeDescription(String changeDescription) {
    this.changeDescription = changeDescription;
  }

  public NewRouteWithStationsDto numberOfBuses(String numberOfBuses) {
    this.numberOfBuses = numberOfBuses;
    return this;
  }

   /**
   * Get numberOfBuses
   * @return numberOfBuses
  **/

  public String getNumberOfBuses() {
    return numberOfBuses;
  }

  public void setNumberOfBuses(String numberOfBuses) {
    this.numberOfBuses = numberOfBuses;
  }

  public NewRouteWithStationsDto intervalOfBuses(String intervalOfBuses) {
    this.intervalOfBuses = intervalOfBuses;
    return this;
  }

   /**
   * Get intervalOfBuses
   * @return intervalOfBuses
  **/

  public String getIntervalOfBuses() {
    return intervalOfBuses;
  }

  public void setIntervalOfBuses(String intervalOfBuses) {
    this.intervalOfBuses = intervalOfBuses;
  }

  public NewRouteWithStationsDto newRouteStatus(NamedEntityDto newRouteStatus) {
    this.newRouteStatus = newRouteStatus;
    return this;
  }

   /**
   * Get newRouteStatus
   * @return newRouteStatus
  **/

  public NamedEntityDto getNewRouteStatus() {
    return newRouteStatus;
  }

  public void setNewRouteStatus(NamedEntityDto newRouteStatus) {
    this.newRouteStatus = newRouteStatus;
  }

  public NewRouteWithStationsDto newRouteBusType(NamedEntityDto newRouteBusType) {
    this.newRouteBusType = newRouteBusType;
    return this;
  }

   /**
   * Get newRouteBusType
   * @return newRouteBusType
  **/

  public NamedEntityDto getNewRouteBusType() {
    return newRouteBusType;
  }

  public void setNewRouteBusType(NamedEntityDto newRouteBusType) {
    this.newRouteBusType = newRouteBusType;
  }

  public NewRouteWithStationsDto id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/

  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public NewRouteWithStationsDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

   /**
   * Get type
   * @return type
  **/

  public TypeEnum getType() {
    return type;
  }

  public NewRouteWithStationsDto forwardDirectionStations(List<Integer> forwardDirectionStations) {
    this.forwardDirectionStations = forwardDirectionStations;
    return this;
  }

  public NewRouteWithStationsDto addForwardDirectionStationsItem(Integer forwardDirectionStationsItem) {
    if (this.forwardDirectionStations == null) {
      this.forwardDirectionStations = new ArrayList<Integer>();
    }
    this.forwardDirectionStations.add(forwardDirectionStationsItem);
    return this;
  }

   /**
   * Get forwardDirectionStations
   * @return forwardDirectionStations
  **/

  public List<Integer> getForwardDirectionStations() {
    return forwardDirectionStations;
  }

  public void setForwardDirectionStations(List<Integer> forwardDirectionStations) {
    this.forwardDirectionStations = forwardDirectionStations;
  }

  public NewRouteWithStationsDto backDirectionStations(List<Integer> backDirectionStations) {
    this.backDirectionStations = backDirectionStations;
    return this;
  }

  public NewRouteWithStationsDto addBackDirectionStationsItem(Integer backDirectionStationsItem) {
    if (this.backDirectionStations == null) {
      this.backDirectionStations = new ArrayList<Integer>();
    }
    this.backDirectionStations.add(backDirectionStationsItem);
    return this;
  }

   /**
   * Get backDirectionStations
   * @return backDirectionStations
  **/

  public List<Integer> getBackDirectionStations() {
    return backDirectionStations;
  }

  public void setBackDirectionStations(List<Integer> backDirectionStations) {
    this.backDirectionStations = backDirectionStations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewRouteWithStationsDto newRouteWithStationsDto = (NewRouteWithStationsDto) o;
    return Objects.equals(this.description, newRouteWithStationsDto.description) &&
        Objects.equals(this.changeDescription, newRouteWithStationsDto.changeDescription) &&
        Objects.equals(this.numberOfBuses, newRouteWithStationsDto.numberOfBuses) &&
        Objects.equals(this.intervalOfBuses, newRouteWithStationsDto.intervalOfBuses) &&
        Objects.equals(this.newRouteStatus, newRouteWithStationsDto.newRouteStatus) &&
        Objects.equals(this.newRouteBusType, newRouteWithStationsDto.newRouteBusType) &&
        Objects.equals(this.id, newRouteWithStationsDto.id) &&
        Objects.equals(this.name, newRouteWithStationsDto.name) &&
        Objects.equals(this.type, newRouteWithStationsDto.type) &&
        Objects.equals(this.forwardDirectionStations, newRouteWithStationsDto.forwardDirectionStations) &&
        Objects.equals(this.backDirectionStations, newRouteWithStationsDto.backDirectionStations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, changeDescription, numberOfBuses, intervalOfBuses, newRouteStatus, newRouteBusType, id, name, type, forwardDirectionStations, backDirectionStations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewRouteWithStationsDto {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    changeDescription: ").append(toIndentedString(changeDescription)).append("\n");
    sb.append("    numberOfBuses: ").append(toIndentedString(numberOfBuses)).append("\n");
    sb.append("    intervalOfBuses: ").append(toIndentedString(intervalOfBuses)).append("\n");
    sb.append("    newRouteStatus: ").append(toIndentedString(newRouteStatus)).append("\n");
    sb.append("    newRouteBusType: ").append(toIndentedString(newRouteBusType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    forwardDirectionStations: ").append(toIndentedString(forwardDirectionStations)).append("\n");
    sb.append("    backDirectionStations: ").append(toIndentedString(backDirectionStations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

