/*
 * Anonymous API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.binwell.dal.dto;

import com.google.gson.annotations.SerializedName;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * ObjectOnlineDto
 */

public class ObjectOnlineDto {
  @SerializedName("averageSpeed")
  private Double averageSpeed = null;

  @SerializedName("minutesLeftToBusStop")
  private Double minutesLeftToBusStop = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("objId")
  private Integer objId = null;

  @SerializedName("lastTime")
  private OffsetDateTime lastTime = null;

  @SerializedName("lastLongitude")
  private Double lastLongitude = null;

  @SerializedName("lastLatitude")
  private Double lastLatitude = null;

  @SerializedName("lastSpeed")
  private Integer lastSpeed = null;

  @SerializedName("projectId")
  private Integer projectId = null;

  @SerializedName("lastStationId")
  private Integer lastStationId = null;

  @SerializedName("lastStationTime")
  private OffsetDateTime lastStationTime = null;

  @SerializedName("lastRouteId")
  private Integer lastRouteId = null;

  @SerializedName("carTypeId")
  private Integer carTypeId = null;

  @SerializedName("azimuth")
  private Integer azimuth = null;

  @SerializedName("providerId")
  private Integer providerId = null;

  @SerializedName("carBrandId")
  private Integer carBrandId = null;

  @SerializedName("userComment")
  private String userComment = null;

  @SerializedName("dateInserted")
  private OffsetDateTime dateInserted = null;

  @SerializedName("objectOutput")
  private Boolean objectOutput = null;

  @SerializedName("objectOutputDate")
  private OffsetDateTime objectOutputDate = null;

  @SerializedName("phone")
  private Long phone = null;

  @SerializedName("yearRelease")
  private Integer yearRelease = null;

  @SerializedName("dispRouteId")
  private Integer dispRouteId = null;

  @SerializedName("lastAddInfo")
  private Integer lastAddInfo = null;

  @SerializedName("lowfloor")
  private Boolean lowfloor = null;

  @SerializedName("statusName")
  private String statusName = null;

  @SerializedName("carBrand")
  private CarBrandDto carBrand = null;

  @SerializedName("provider")
  private ProviderDto provider = null;

  @SerializedName("route")
  private RouteDto route = null;

  @SerializedName("project")
  private ProjectDto project = null;

  @SerializedName("block")
  private GranitDto block = null;

  public ObjectOnlineDto averageSpeed(Double averageSpeed) {
    this.averageSpeed = averageSpeed;
    return this;
  }

   /**
   * Get averageSpeed
   * @return averageSpeed
  **/

  public Double getAverageSpeed() {
    return averageSpeed;
  }

  public void setAverageSpeed(Double averageSpeed) {
    this.averageSpeed = averageSpeed;
  }

  public ObjectOnlineDto minutesLeftToBusStop(Double minutesLeftToBusStop) {
    this.minutesLeftToBusStop = minutesLeftToBusStop;
    return this;
  }

   /**
   * Get minutesLeftToBusStop
   * @return minutesLeftToBusStop
  **/

  public Double getMinutesLeftToBusStop() {
    return minutesLeftToBusStop;
  }

  public void setMinutesLeftToBusStop(Double minutesLeftToBusStop) {
    this.minutesLeftToBusStop = minutesLeftToBusStop;
  }

  public ObjectOnlineDto id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/

  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ObjectOnlineDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ObjectOnlineDto objId(Integer objId) {
    this.objId = objId;
    return this;
  }

   /**
   * Get objId
   * @return objId
  **/

  public Integer getObjId() {
    return objId;
  }

  public void setObjId(Integer objId) {
    this.objId = objId;
  }

  public ObjectOnlineDto lastTime(OffsetDateTime lastTime) {
    this.lastTime = lastTime;
    return this;
  }

   /**
   * Get lastTime
   * @return lastTime
  **/

  public OffsetDateTime getLastTime() {
    return lastTime;
  }

  public void setLastTime(OffsetDateTime lastTime) {
    this.lastTime = lastTime;
  }

  public ObjectOnlineDto lastLongitude(Double lastLongitude) {
    this.lastLongitude = lastLongitude;
    return this;
  }

   /**
   * Get lastLongitude
   * @return lastLongitude
  **/

  public Double getLastLongitude() {
    return lastLongitude;
  }

  public void setLastLongitude(Double lastLongitude) {
    this.lastLongitude = lastLongitude;
  }

  public ObjectOnlineDto lastLatitude(Double lastLatitude) {
    this.lastLatitude = lastLatitude;
    return this;
  }

   /**
   * Get lastLatitude
   * @return lastLatitude
  **/

  public Double getLastLatitude() {
    return lastLatitude;
  }

  public void setLastLatitude(Double lastLatitude) {
    this.lastLatitude = lastLatitude;
  }

  public ObjectOnlineDto lastSpeed(Integer lastSpeed) {
    this.lastSpeed = lastSpeed;
    return this;
  }

   /**
   * Get lastSpeed
   * @return lastSpeed
  **/

  public Integer getLastSpeed() {
    return lastSpeed;
  }

  public void setLastSpeed(Integer lastSpeed) {
    this.lastSpeed = lastSpeed;
  }

  public ObjectOnlineDto projectId(Integer projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/

  public Integer getProjectId() {
    return projectId;
  }

  public void setProjectId(Integer projectId) {
    this.projectId = projectId;
  }

  public ObjectOnlineDto lastStationId(Integer lastStationId) {
    this.lastStationId = lastStationId;
    return this;
  }

   /**
   * Get lastStationId
   * @return lastStationId
  **/

  public Integer getLastStationId() {
    return lastStationId;
  }

  public void setLastStationId(Integer lastStationId) {
    this.lastStationId = lastStationId;
  }

  public ObjectOnlineDto lastStationTime(OffsetDateTime lastStationTime) {
    this.lastStationTime = lastStationTime;
    return this;
  }

   /**
   * Get lastStationTime
   * @return lastStationTime
  **/

  public OffsetDateTime getLastStationTime() {
    return lastStationTime;
  }

  public void setLastStationTime(OffsetDateTime lastStationTime) {
    this.lastStationTime = lastStationTime;
  }

  public ObjectOnlineDto lastRouteId(Integer lastRouteId) {
    this.lastRouteId = lastRouteId;
    return this;
  }

   /**
   * Get lastRouteId
   * @return lastRouteId
  **/

  public Integer getLastRouteId() {
    return lastRouteId;
  }

  public void setLastRouteId(Integer lastRouteId) {
    this.lastRouteId = lastRouteId;
  }

  public ObjectOnlineDto carTypeId(Integer carTypeId) {
    this.carTypeId = carTypeId;
    return this;
  }

   /**
   * Get carTypeId
   * @return carTypeId
  **/

  public Integer getCarTypeId() {
    return carTypeId;
  }

  public void setCarTypeId(Integer carTypeId) {
    this.carTypeId = carTypeId;
  }

  public ObjectOnlineDto azimuth(Integer azimuth) {
    this.azimuth = azimuth;
    return this;
  }

   /**
   * Get azimuth
   * @return azimuth
  **/

  public Integer getAzimuth() {
    return azimuth;
  }

  public void setAzimuth(Integer azimuth) {
    this.azimuth = azimuth;
  }

  public ObjectOnlineDto providerId(Integer providerId) {
    this.providerId = providerId;
    return this;
  }

   /**
   * Get providerId
   * @return providerId
  **/

  public Integer getProviderId() {
    return providerId;
  }

  public void setProviderId(Integer providerId) {
    this.providerId = providerId;
  }

  public ObjectOnlineDto carBrandId(Integer carBrandId) {
    this.carBrandId = carBrandId;
    return this;
  }

   /**
   * Get carBrandId
   * @return carBrandId
  **/

  public Integer getCarBrandId() {
    return carBrandId;
  }

  public void setCarBrandId(Integer carBrandId) {
    this.carBrandId = carBrandId;
  }

  public ObjectOnlineDto userComment(String userComment) {
    this.userComment = userComment;
    return this;
  }

   /**
   * Get userComment
   * @return userComment
  **/

  public String getUserComment() {
    return userComment;
  }

  public void setUserComment(String userComment) {
    this.userComment = userComment;
  }

  public ObjectOnlineDto dateInserted(OffsetDateTime dateInserted) {
    this.dateInserted = dateInserted;
    return this;
  }

   /**
   * Get dateInserted
   * @return dateInserted
  **/

  public OffsetDateTime getDateInserted() {
    return dateInserted;
  }

  public void setDateInserted(OffsetDateTime dateInserted) {
    this.dateInserted = dateInserted;
  }

  public ObjectOnlineDto objectOutput(Boolean objectOutput) {
    this.objectOutput = objectOutput;
    return this;
  }

   /**
   * Get objectOutput
   * @return objectOutput
  **/

  public Boolean isObjectOutput() {
    return objectOutput;
  }

  public void setObjectOutput(Boolean objectOutput) {
    this.objectOutput = objectOutput;
  }

  public ObjectOnlineDto objectOutputDate(OffsetDateTime objectOutputDate) {
    this.objectOutputDate = objectOutputDate;
    return this;
  }

   /**
   * Get objectOutputDate
   * @return objectOutputDate
  **/

  public OffsetDateTime getObjectOutputDate() {
    return objectOutputDate;
  }

  public void setObjectOutputDate(OffsetDateTime objectOutputDate) {
    this.objectOutputDate = objectOutputDate;
  }

  public ObjectOnlineDto phone(Long phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/

  public Long getPhone() {
    return phone;
  }

  public void setPhone(Long phone) {
    this.phone = phone;
  }

  public ObjectOnlineDto yearRelease(Integer yearRelease) {
    this.yearRelease = yearRelease;
    return this;
  }

   /**
   * Get yearRelease
   * @return yearRelease
  **/

  public Integer getYearRelease() {
    return yearRelease;
  }

  public void setYearRelease(Integer yearRelease) {
    this.yearRelease = yearRelease;
  }

  public ObjectOnlineDto dispRouteId(Integer dispRouteId) {
    this.dispRouteId = dispRouteId;
    return this;
  }

   /**
   * Get dispRouteId
   * @return dispRouteId
  **/

  public Integer getDispRouteId() {
    return dispRouteId;
  }

  public void setDispRouteId(Integer dispRouteId) {
    this.dispRouteId = dispRouteId;
  }

  public ObjectOnlineDto lastAddInfo(Integer lastAddInfo) {
    this.lastAddInfo = lastAddInfo;
    return this;
  }

   /**
   * Get lastAddInfo
   * @return lastAddInfo
  **/

  public Integer getLastAddInfo() {
    return lastAddInfo;
  }

  public void setLastAddInfo(Integer lastAddInfo) {
    this.lastAddInfo = lastAddInfo;
  }

  public ObjectOnlineDto lowfloor(Boolean lowfloor) {
    this.lowfloor = lowfloor;
    return this;
  }

   /**
   * Get lowfloor
   * @return lowfloor
  **/

  public Boolean isLowfloor() {
    return lowfloor;
  }

  public void setLowfloor(Boolean lowfloor) {
    this.lowfloor = lowfloor;
  }

  public ObjectOnlineDto statusName(String statusName) {
    this.statusName = statusName;
    return this;
  }

   /**
   * Get statusName
   * @return statusName
  **/

  public String getStatusName() {
    return statusName;
  }

  public void setStatusName(String statusName) {
    this.statusName = statusName;
  }

  public ObjectOnlineDto carBrand(CarBrandDto carBrand) {
    this.carBrand = carBrand;
    return this;
  }

   /**
   * Get carBrand
   * @return carBrand
  **/

  public CarBrandDto getCarBrand() {
    return carBrand;
  }

  public void setCarBrand(CarBrandDto carBrand) {
    this.carBrand = carBrand;
  }

  public ObjectOnlineDto provider(ProviderDto provider) {
    this.provider = provider;
    return this;
  }

   /**
   * Get provider
   * @return provider
  **/

  public ProviderDto getProvider() {
    return provider;
  }

  public void setProvider(ProviderDto provider) {
    this.provider = provider;
  }

  public ObjectOnlineDto route(RouteDto route) {
    this.route = route;
    return this;
  }

   /**
   * Get route
   * @return route
  **/

  public RouteDto getRoute() {
    return route;
  }

  public void setRoute(RouteDto route) {
    this.route = route;
  }

  public ObjectOnlineDto project(ProjectDto project) {
    this.project = project;
    return this;
  }

   /**
   * Get project
   * @return project
  **/

  public ProjectDto getProject() {
    return project;
  }

  public void setProject(ProjectDto project) {
    this.project = project;
  }

  public ObjectOnlineDto block(GranitDto block) {
    this.block = block;
    return this;
  }

   /**
   * Get block
   * @return block
  **/

  public GranitDto getBlock() {
    return block;
  }

  public void setBlock(GranitDto block) {
    this.block = block;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjectOnlineDto objectOnlineDto = (ObjectOnlineDto) o;
    return Objects.equals(this.averageSpeed, objectOnlineDto.averageSpeed) &&
        Objects.equals(this.minutesLeftToBusStop, objectOnlineDto.minutesLeftToBusStop) &&
        Objects.equals(this.id, objectOnlineDto.id) &&
        Objects.equals(this.name, objectOnlineDto.name) &&
        Objects.equals(this.objId, objectOnlineDto.objId) &&
        Objects.equals(this.lastTime, objectOnlineDto.lastTime) &&
        Objects.equals(this.lastLongitude, objectOnlineDto.lastLongitude) &&
        Objects.equals(this.lastLatitude, objectOnlineDto.lastLatitude) &&
        Objects.equals(this.lastSpeed, objectOnlineDto.lastSpeed) &&
        Objects.equals(this.projectId, objectOnlineDto.projectId) &&
        Objects.equals(this.lastStationId, objectOnlineDto.lastStationId) &&
        Objects.equals(this.lastStationTime, objectOnlineDto.lastStationTime) &&
        Objects.equals(this.lastRouteId, objectOnlineDto.lastRouteId) &&
        Objects.equals(this.carTypeId, objectOnlineDto.carTypeId) &&
        Objects.equals(this.azimuth, objectOnlineDto.azimuth) &&
        Objects.equals(this.providerId, objectOnlineDto.providerId) &&
        Objects.equals(this.carBrandId, objectOnlineDto.carBrandId) &&
        Objects.equals(this.userComment, objectOnlineDto.userComment) &&
        Objects.equals(this.dateInserted, objectOnlineDto.dateInserted) &&
        Objects.equals(this.objectOutput, objectOnlineDto.objectOutput) &&
        Objects.equals(this.objectOutputDate, objectOnlineDto.objectOutputDate) &&
        Objects.equals(this.phone, objectOnlineDto.phone) &&
        Objects.equals(this.yearRelease, objectOnlineDto.yearRelease) &&
        Objects.equals(this.dispRouteId, objectOnlineDto.dispRouteId) &&
        Objects.equals(this.lastAddInfo, objectOnlineDto.lastAddInfo) &&
        Objects.equals(this.lowfloor, objectOnlineDto.lowfloor) &&
        Objects.equals(this.statusName, objectOnlineDto.statusName) &&
        Objects.equals(this.carBrand, objectOnlineDto.carBrand) &&
        Objects.equals(this.provider, objectOnlineDto.provider) &&
        Objects.equals(this.route, objectOnlineDto.route) &&
        Objects.equals(this.project, objectOnlineDto.project) &&
        Objects.equals(this.block, objectOnlineDto.block);
  }

  @Override
  public int hashCode() {
    return Objects.hash(averageSpeed, minutesLeftToBusStop, id, name, objId, lastTime, lastLongitude, lastLatitude, lastSpeed, projectId, lastStationId, lastStationTime, lastRouteId, carTypeId, azimuth, providerId, carBrandId, userComment, dateInserted, objectOutput, objectOutputDate, phone, yearRelease, dispRouteId, lastAddInfo, lowfloor, statusName, carBrand, provider, route, project, block);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjectOnlineDto {\n");
    
    sb.append("    averageSpeed: ").append(toIndentedString(averageSpeed)).append("\n");
    sb.append("    minutesLeftToBusStop: ").append(toIndentedString(minutesLeftToBusStop)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    objId: ").append(toIndentedString(objId)).append("\n");
    sb.append("    lastTime: ").append(toIndentedString(lastTime)).append("\n");
    sb.append("    lastLongitude: ").append(toIndentedString(lastLongitude)).append("\n");
    sb.append("    lastLatitude: ").append(toIndentedString(lastLatitude)).append("\n");
    sb.append("    lastSpeed: ").append(toIndentedString(lastSpeed)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    lastStationId: ").append(toIndentedString(lastStationId)).append("\n");
    sb.append("    lastStationTime: ").append(toIndentedString(lastStationTime)).append("\n");
    sb.append("    lastRouteId: ").append(toIndentedString(lastRouteId)).append("\n");
    sb.append("    carTypeId: ").append(toIndentedString(carTypeId)).append("\n");
    sb.append("    azimuth: ").append(toIndentedString(azimuth)).append("\n");
    sb.append("    providerId: ").append(toIndentedString(providerId)).append("\n");
    sb.append("    carBrandId: ").append(toIndentedString(carBrandId)).append("\n");
    sb.append("    userComment: ").append(toIndentedString(userComment)).append("\n");
    sb.append("    dateInserted: ").append(toIndentedString(dateInserted)).append("\n");
    sb.append("    objectOutput: ").append(toIndentedString(objectOutput)).append("\n");
    sb.append("    objectOutputDate: ").append(toIndentedString(objectOutputDate)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    yearRelease: ").append(toIndentedString(yearRelease)).append("\n");
    sb.append("    dispRouteId: ").append(toIndentedString(dispRouteId)).append("\n");
    sb.append("    lastAddInfo: ").append(toIndentedString(lastAddInfo)).append("\n");
    sb.append("    lowfloor: ").append(toIndentedString(lowfloor)).append("\n");
    sb.append("    statusName: ").append(toIndentedString(statusName)).append("\n");
    sb.append("    carBrand: ").append(toIndentedString(carBrand)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    route: ").append(toIndentedString(route)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    block: ").append(toIndentedString(block)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

