/*
 * Anonymous API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.binwell.dal.dto;

import com.google.gson.annotations.SerializedName;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ObjectOnlineResponse
 */

public class ObjectOnlineResponse {
  @SerializedName("serverTime")
  private OffsetDateTime serverTime = null;

  @SerializedName("buses")
  private List<ObjectOnlineDto> buses = null;

   /**
   * Get serverTime
   * @return serverTime
  **/

  public OffsetDateTime getServerTime() {
    return serverTime;
  }

  public ObjectOnlineResponse buses(List<ObjectOnlineDto> buses) {
    this.buses = buses;
    return this;
  }

  public ObjectOnlineResponse addBusesItem(ObjectOnlineDto busesItem) {
    if (this.buses == null) {
      this.buses = new ArrayList<ObjectOnlineDto>();
    }
    this.buses.add(busesItem);
    return this;
  }

   /**
   * Get buses
   * @return buses
  **/

  public List<ObjectOnlineDto> getBuses() {
    return buses;
  }

  public void setBuses(List<ObjectOnlineDto> buses) {
    this.buses = buses;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjectOnlineResponse objectOnlineResponse = (ObjectOnlineResponse) o;
    return Objects.equals(this.serverTime, objectOnlineResponse.serverTime) &&
        Objects.equals(this.buses, objectOnlineResponse.buses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serverTime, buses);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjectOnlineResponse {\n");
    
    sb.append("    serverTime: ").append(toIndentedString(serverTime)).append("\n");
    sb.append("    buses: ").append(toIndentedString(buses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

